// etherealgems-nextjs/pages/checkout.tsx
import { useEffect, useState } from 'react'
import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
import Layout from '@/components/Layout'
import { useCartStoreSSR } from '@/stores/useCartStore'
import { useAuthStore } from '@/stores/useAuthStore'
import { formatPriceSimple } from '@/utils/formatPrice'

export default function Checkout() {
  const router = useRouter()
  const { items, getTotalPrice, clearCart, isHydrated } = useCartStoreSSR()
  const { isLoggedIn } = useAuthStore()
  const [formData, setFormData] = useState({
    firstName: '',
    lastName: '',
    email: '',
    phone: '',
    address: '',
    city: '',
    postalCode: '',
    paymentMethod: 'razorpay'
  })
  const [isProcessing, setIsProcessing] = useState(false)

  useEffect(() => {
    if (isHydrated && items.length === 0) {
      router.push('/shop')
    }
  }, [items, isHydrated, router])

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value
    })
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setIsProcessing(true)
    
    // Simulate order processing
    setTimeout(() => {
      alert('Order placed successfully! This is a demo - no actual payment was processed.')
      clearCart()
      router.push('/')
    }, 2000)
  }

  if (!isHydrated) {
    return (
      <Layout>
        <div className="flex justify-center items-center h-64">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-600"></div>
        </div>
      </Layout>
    )
  }

  if (items.length === 0) {
    return (
      <Layout>
        <div className="max-w-2xl mx-auto px-4 py-16 text-center">
          <h1 className="text-2xl font-bold mb-4">Your cart is empty</h1>
          <Link href="/shop" className="bg-primary-600 text-white px-6 py-3 rounded-lg hover:bg-primary-700 transition-colors">
            Continue Shopping
          </Link>
        </div>
      </Layout>
    )
  }

  return (
    <>
      <Head>
        <title>Checkout - EtherealGems</title>
        <meta name="description" content="Complete your jewelry purchase securely." />
      </Head>
      <Layout>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          <h1 className="text-3xl font-bold text-gray-900 mb-8 font-poppins">Checkout</h1>
          
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
            {/* Order Summary */}
            <div className="order-2 lg:order-1">
              <div className="bg-gray-50 p-6 rounded-lg">
                <h2 className="text-xl font-semibold mb-4">Order Summary</h2>
                <div className="space-y-4">
                  {items.map((item) => (
                    <div key={item._id} className="flex items-center space-x-3">
                      <img
                        src={item.image}
                        alt={item.name}
                        className="w-16 h-16 object-cover rounded"
                      />
                      <div className="flex-1">
                        <h3 className="font-medium">{item.name}</h3>
                        <p className="text-gray-600">Qty: {item.quantity}</p>
                      </div>
                      <span className="font-semibold">₹{formatPriceSimple(item.price * item.quantity)}</span>
                    </div>
                  ))}
                </div>
                <div className="border-t mt-4 pt-4">
                  <div className="flex justify-between text-xl font-bold">
                    <span>Total:</span>
                    <span className="text-primary-600">₹{formatPriceSimple(getTotalPrice())}</span>
                  </div>
                </div>
              </div>
            </div>

            {/* Checkout Form */}
            <div className="order-1 lg:order-2">
              <form onSubmit={handleSubmit} className="space-y-6">
                <div>
                  <h2 className="text-xl font-semibold mb-4">Shipping Information</h2>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-1">
                        First Name *
                      </label>
                      <input
                        type="text"
                        name="firstName"
                        required
                        value={formData.firstName}
                        onChange={handleInputChange}
                        className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent"
                      />
                    </div>
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-1">
                        Last Name *
                      </label>
                      <input
                        type="text"
                        name="lastName"
                        required
                        value={formData.lastName}
                        onChange={handleInputChange}
                        className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent"
                      />
                    </div>
                  </div>
                  
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4">
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-1">
                        Email *
                      </label>
                      <input
                        type="email"
                        name="email"
                        required
                        value={formData.email}
                        onChange={handleInputChange}
                        className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent"
                      />
                    </div>
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-1">
                        Phone *
                      </label>
                      <input
                        type="tel"
                        name="phone"
                        required
                        value={formData.phone}
                        onChange={handleInputChange}
                        className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent"
                      />
                    </div>
                  </div>

                  <div className="mt-4">
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      Address *
                    </label>
                    <textarea
                      name="address"
                      required
                      value={formData.address}
                      onChange={handleInputChange}
                      rows={3}
                      className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent"
                    />
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4">
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-1">
                        City *
                      </label>
                      <input
                        type="text"
                        name="city"
                        required
                        value={formData.city}
                        onChange={handleInputChange}
                        className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent"
                      />
                    </div>
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-1">
                        Postal Code *
                      </label>
                      <input
                        type="text"
                        name="postalCode"
                        required
                        value={formData.postalCode}
                        onChange={handleInputChange}
                        className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent"
                      />
                    </div>
                  </div>
                </div>

                <div>
                  <h2 className="text-xl font-semibold mb-4">Payment Method</h2>
                  <div className="space-y-3">
                    <label className="flex items-center">
                      <input
                        type="radio"
                        name="paymentMethod"
                        value="razorpay"
                        checked={formData.paymentMethod === 'razorpay'}
                        onChange={handleInputChange}
                        className="mr-3"
                      />
                      <span>UPI / Card / Net Banking (Razorpay)</span>
                    </label>
                    <label className="flex items-center">
                      <input
                        type="radio"
                        name="paymentMethod"
                        value="cod"
                        checked={formData.paymentMethod === 'cod'}
                        onChange={handleInputChange}
                        className="mr-3"
                      />
                      <span>Cash on Delivery</span>
                    </label>
                  </div>
                </div>

                <button
                  type="submit"
                  disabled={isProcessing}
                  className="w-full bg-gradient-to-r from-primary-600 to-primary-700 text-white py-4 rounded-lg font-semibold hover:from-primary-700 hover:to-primary-800 transition-all duration-200 disabled:opacity-50 disabled:cursor-not-allowed transform hover:scale-105"
                >
                  {isProcessing ? (
                    <span className="flex items-center justify-center">
                      <svg className="animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                        <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                      </svg>
                      Processing...
                    </span>
                  ) : (
                    `Place Order - ₹${formatPriceSimple(getTotalPrice())}`
                  )}
                </button>
              </form>
            </div>
          </div>
        </div>
      </Layout>
    </>
  )
}

// etherealgems-frontend/src/views/Checkout.vue
<template>
  <div class="bg-gray-50 min-h-screen py-8">
    <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="text-center mb-8">
        <h1 class="text-3xl font-extrabold text-gray-900 font-poppins">Checkout</h1>
        <p class="mt-2 text-gray-600">Complete your order</p>
      </div>

      <div class="lg:grid lg:grid-cols-2 lg:gap-8">
        <!-- Checkout Form -->
        <div class="lg:col-span-1">
          <form @submit.prevent="processOrder" class="space-y-6">
            <!-- Contact Information -->
            <div class="bg-white rounded-lg shadow-md p-6">
              <h2 class="text-lg font-medium text-gray-900 mb-4">Contact Information</h2>
              <div class="space-y-4">
                <div>
                  <label for="email" class="block text-sm font-medium text-gray-700">Email address</label>
                  <input
                    id="email"
                    v-model="orderForm.email"
                    type="email"
                    required
                    class="input-field mt-1"
                    placeholder="Enter your email"
                  />
                </div>
                <div>
                  <label for="phone" class="block text-sm font-medium text-gray-700">Phone number</label>
                  <input
                    id="phone"
                    v-model="orderForm.phone"
                    type="tel"
                    required
                    class="input-field mt-1"
                    placeholder="Enter your phone number"
                  />
                </div>
              </div>
            </div>

            <!-- Shipping Address -->
            <div class="bg-white rounded-lg shadow-md p-6">
              <h2 class="text-lg font-medium text-gray-900 mb-4">Shipping Address</h2>
              <div class="space-y-4">
                <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div>
                    <label for="firstName" class="block text-sm font-medium text-gray-700">First name</label>
                    <input
                      id="firstName"
                      name="firstName"
                      v-model="orderForm.firstName"
                      type="text"
                      required
                      autocomplete="given-name"
                      class="input-field mt-1"
                    />
                  </div>
                  <div>
                    <label for="lastName" class="block text-sm font-medium text-gray-700">Last name</label>
                    <input
                      id="lastName"
                      name="lastName"
                      v-model="orderForm.lastName"
                      type="text"
                      required
                      autocomplete="family-name"
                      class="input-field mt-1"
                    />
                  </div>
                </div>
                
                <div>
                  <label for="address" class="block text-sm font-medium text-gray-700">Address</label>
                  <input
                    id="address"
                    name="address"
                    v-model="orderForm.address"
                    type="text"
                    required
                    autocomplete="street-address"
                    class="input-field mt-1"
                    placeholder="Street address"
                  />
                </div>
                
                <div class="grid grid-cols-1 sm:grid-cols-3 gap-4">
                  <div>
                    <label for="city" class="block text-sm font-medium text-gray-700">City</label>
                    <input
                      id="city"
                      name="city"
                      v-model="orderForm.city"
                      type="text"
                      required
                      autocomplete="address-level2"
                      class="input-field mt-1"
                    />
                  </div>
                  <div>
                    <label for="state" class="block text-sm font-medium text-gray-700">State</label>
                    <select
                      id="state"
                      name="state"
                      v-model="orderForm.state"
                      required
                      autocomplete="address-level1"
                      class="input-field mt-1"
                    >
                      <option value="">Select State</option>
                      <option value="Maharashtra">Maharashtra</option>
                      <option value="Delhi">Delhi</option>
                      <option value="Karnataka">Karnataka</option>
                      <option value="Gujarat">Gujarat</option>
                      <option value="Tamil Nadu">Tamil Nadu</option>
                      <option value="West Bengal">West Bengal</option>
                      <!-- Add more states as needed -->
                    </select>
                  </div>
                  <div>
                    <label for="pincode" class="block text-sm font-medium text-gray-700">PIN Code</label>
                    <input
                      id="pincode"
                      name="pincode"
                      v-model="orderForm.pincode"
                      type="text"
                      required
                      autocomplete="postal-code"
                      class="input-field mt-1"
                      pattern="[0-9]{6}"
                      maxlength="6"
                    />
                  </div>
                </div>
              </div>
            </div>

            <!-- Payment Method -->
            <div class="bg-white rounded-lg shadow-md p-6">
              <h2 class="text-lg font-medium text-gray-900 mb-4">Payment Method</h2>
              <div class="space-y-4">
                <div class="flex items-center">
                  <input
                    id="upi"
                    name="paymentMethod"
                    v-model="orderForm.paymentMethod"
                    type="radio"
                    value="upi"
                    class="text-primary-600 focus:ring-primary-500"
                  />
                  <label for="upi" class="ml-3 block text-sm font-medium text-gray-700">
                    UPI (Google Pay, PhonePe, Paytm)
                  </label>
                </div>
                <div class="flex items-center">
                  <input
                    id="card"
                    name="paymentMethod"
                    v-model="orderForm.paymentMethod"
                    type="radio"
                    value="card"
                    class="text-primary-600 focus:ring-primary-500"
                  />
                  <label for="card" class="ml-3 block text-sm font-medium text-gray-700">
                    Credit/Debit Card
                  </label>
                </div>
                <div class="flex items-center">
                  <input
                    id="cod"
                    name="paymentMethod"
                    v-model="orderForm.paymentMethod"
                    type="radio"
                    value="cod"
                    class="text-primary-600 focus:ring-primary-500"
                  />
                  <label for="cod" class="ml-3 block text-sm font-medium text-gray-700">
                    Cash on Delivery
                  </label>
                </div>
              </div>
            </div>

            <!-- Order Notes -->
            <div class="bg-white rounded-lg shadow-md p-6">
              <h2 class="text-lg font-medium text-gray-900 mb-4">Order Notes (Optional)</h2>
              <textarea
                id="orderNotes"
                name="orderNotes"
                v-model="orderForm.notes"
                rows="3"
                autocomplete="off"
                class="input-field"
                placeholder="Any special instructions for your order..."
              ></textarea>
            </div>
          </form>
        </div>

        <!-- Order Summary -->
        <div class="lg:col-span-1 mt-8 lg:mt-0">
          <div class="bg-white rounded-lg shadow-md p-6 sticky top-8">
            <h2 class="text-lg font-medium text-gray-900 mb-4">Order Summary</h2>
            
            <!-- Order Items -->
            <div class="space-y-4 mb-6">
              <div
                v-for="item in cartStore.cartItems"
                :key="item.id"
                class="flex items-center space-x-4"
              >
                <div class="flex-shrink-0">
                  <img
                    :src="item.image"
                    :alt="item.name"
                    class="w-16 h-16 object-center object-cover rounded-md border border-gray-200"
                  />
                </div>
                <div class="flex-1">
                  <h3 class="text-sm font-medium text-gray-900">{{ item.name }}</h3>
                  <p class="text-sm text-gray-500">Qty: {{ item.quantity }}</p>
                </div>
                <div class="text-sm font-medium text-gray-900">
                  ₹{{ (item.price * item.quantity).toLocaleString() }}
                </div>
              </div>
            </div>
            
            <!-- Pricing Details -->
            <div class="border-t border-gray-200 pt-4 space-y-3">
              <div class="flex justify-between text-sm">
                <span class="text-gray-600">Subtotal</span>
                <span class="text-gray-900">₹{{ cartStore.totalPrice.toLocaleString() }}</span>
              </div>
              
              <div class="flex justify-between text-sm">
                <span class="text-gray-600">Shipping</span>
                <span class="text-green-600">Free</span>
              </div>
              
              <div class="flex justify-between text-sm">
                <span class="text-gray-600">Tax (18% GST)</span>
                <span class="text-gray-900">₹{{ Math.round(cartStore.totalPrice * 0.18).toLocaleString() }}</span>
              </div>
              
              <div class="border-t border-gray-200 pt-3">
                <div class="flex justify-between text-base font-medium">
                  <span class="text-gray-900">Total</span>
                  <span class="text-gray-900">₹{{ orderTotal.toLocaleString() }}</span>
                </div>
              </div>
            </div>
            
            <!-- Place Order Button -->
            <button
              @click="processOrder"
              :disabled="!isFormValid || processing"
              class="w-full mt-6 bg-primary-600 text-white py-3 px-4 rounded-md font-medium hover:bg-primary-700 disabled:bg-gray-400 disabled:cursor-not-allowed transition-colors duration-200"
            >
              <span v-if="processing" class="flex items-center justify-center">
                <svg class="animate-spin -ml-1 mr-3 h-5 w-5 text-white" fill="none" viewBox="0 0 24 24">
                  <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                  <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                </svg>
                Processing...
              </span>
              <span v-else>Place Order - ₹{{ orderTotal.toLocaleString() }}</span>
            </button>
            
            <!-- Security Badge -->
            <div class="mt-4 flex items-center justify-center text-sm text-gray-500">
              <svg class="w-4 h-4 text-green-500 mr-2" fill="currentColor" viewBox="0 0 20 20">
                <path fill-rule="evenodd" d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z" clip-rule="evenodd" />
              </svg>
              Secure checkout powered by Razorpay
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed } from 'vue'
import { useRouter } from 'vue-router'
import { useCartStore } from '../stores/cart'

const router = useRouter()
const cartStore = useCartStore()

const processing = ref(false)

const orderForm = ref({
  email: '',
  phone: '',
  firstName: '',
  lastName: '',
  address: '',
  city: '',
  state: '',
  pincode: '',
  paymentMethod: 'upi',
  notes: ''
})

const orderTotal = computed(() => {
  return Math.round(cartStore.totalPrice * 1.18) // Including 18% GST
})

const isFormValid = computed(() => {
  const form = orderForm.value
  return form.email && form.phone && form.firstName && form.lastName && 
         form.address && form.city && form.state && form.pincode && 
         form.paymentMethod && cartStore.cartItems.length > 0
})

const processOrder = async () => {
  if (!isFormValid.value) {
    alert('Please fill in all required fields')
    return
  }
  
  processing.value = true
  
  try {
    // Simulate order processing
    await new Promise(resolve => setTimeout(resolve, 2000))
    
    // Here you would integrate with Razorpay for payment processing
    console.log('Order processed:', {
      items: cartStore.cartItems,
      total: orderTotal.value,
      customer: orderForm.value
    })
    
    // Clear cart after successful order
    cartStore.clearCart()
    
    // Redirect to success page or show success message
    alert('Order placed successfully! You will receive a confirmation email shortly.')
    router.push('/')
    
  } catch (error) {
    console.error('Order processing failed:', error)
    alert('Order processing failed. Please try again.')
  } finally {
    processing.value = false
  }
}
</script>
